# ──────────────── 修正後の netlify.toml ────────────────
[build]
  command   = "astro build"
  functions = "netlify/functions"
  publish   = "dist"

# ─ 以下のプラグイン関連設定はまるごと削除しました ─
# [[plugins]]
#   package = "netlify-plugin-cypress"
#
# [plugins.inputs.postBuild]
#   enable = true
#
# [plugins.inputs]
#   enable = false
# ─────────────────────────────────────────────────────────